apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "* * * * *"  
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjob-hello"
        spec:
          containers:
          - name: hello-cron
            image: quay.io/hatland87/hello-cron
            command:
              - "/opt/script.sh"
          restartPolicy: OnFailure 